# Primarily based on the docker-compose.yml file example at:
#   https://hub.docker.com/_/wordpress/
# See this article for an alternative approach:
#   https://docs.docker.com/compose/wordpress/

wordpress:
  build: .
  links:
    - db:mysql
  ports:
    - 8080:80

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
