wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - ./wp-web-push/wp-web-push:/var/www/html/wp-content/plugins/wp-web-push

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
